/**
 * ============================================================================
 * KOWA RIDE - SUPERADMIN DASHBOARD
 * Mock Data for Development & Demonstration
 * ============================================================================
 *
 * This file provides realistic mock data for all dashboard modules.
 * Data is designed to represent a Nigerian ride-hailing operation with
 * authentic names, locations, and financial figures in Naira (₦).
 *
 * In production, this data will be replaced by API calls to the backend.
 *
 * @module lib/mock-data
 * @version 1.0.0
 * @author Kowa Ride Engineering Team
 * ============================================================================
 */

import {
  Rider,
  FleetManager,
  FleetOwner,
  BikeAsset,
  Transaction,
  PayoutSummary,
  SystemAlert,
  RiskAssessment,
  AuditLogEntry,
  PlatformKPIs,
  ChartDataPoint,
  ActivityItem,
  AllocationBreakdown,
  SystemConfig,
  UserRole,
  KycStatus,
  RiderStatus,
  PerformanceTier,
  RiskLevel,
  AssetStatus,
  TransactionType,
  TransactionStatus,
  AlertSeverity,
  UnpaidDayAction,
} from "@/types/admin";

// ============================================================================
// PLATFORM KPIs
// ============================================================================

export const mockKPIs: PlatformKPIs = {
  totalRiders: 3847,
  activeRiders: 3214,
  totalFleetManagers: 86,
  totalFleetOwners: 23,
  totalBikes: 3456,
  activeBikes: 3198,
  fleetUtilizationRate: 92.5,
  avgRepaymentRate: 87.3,
  todayRevenue: 4872500,
  monthlyRevenue: 145200000,
  totalOutstandingPayments: 23450000,
  unresolvedAlerts: 14,
  criticalRiskItems: 3,
  pendingPayouts: 18750000,
};

// ============================================================================
// RIDERS
// ============================================================================

export const mockRiders: Rider[] = [
  {
    id: "rider-001",
    firstName: "Chukwuemeka",
    lastName: "Okonkwo",
    email: "c.okonkwo@email.com",
    phone: "+234 801 234 5678",
    avatarUrl: "https://i.pravatar.cc/80?img=11",
    role: UserRole.RIDER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE,
    riderId: "KR-2024-00123",
    assignedBikeId: "bike-012",
    fleetManagerId: "fm-001",
    dailyPaymentAmount: 3500,
    totalPaidToDate: 630000,
    paymentStreak: 24,
    repaymentRate: 98.5,
    hmoEnrolled: true,
    ownershipProgressMonths: 6,
    lastKnownLocation: { latitude: 6.5244, longitude: 3.3792 },
    accountBalance: 0,
    unpaidDays: 0,
    unpaidDayAction: UnpaidDayAction.NONE,
    createdAt: "2024-07-15T08:00:00Z",
    lastActiveAt: "2025-01-15T18:30:00Z",
  },
  {
    id: "rider-002",
    firstName: "Aishat",
    lastName: "Abubakar",
    email: "a.abubakar@email.com",
    phone: "+234 802 345 6789",
    avatarUrl: "https://i.pravatar.cc/80?img=5",
    role: UserRole.RIDER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE,
    riderId: "KR-2024-00456",
    assignedBikeId: "bike-023",
    fleetManagerId: "fm-001",
    dailyPaymentAmount: 3500,
    totalPaidToDate: 525000,
    paymentStreak: 18,
    repaymentRate: 95.2,
    hmoEnrolled: true,
    ownershipProgressMonths: 5,
    lastKnownLocation: { latitude: 6.4541, longitude: 3.3947 },
    accountBalance: 3500,
    unpaidDays: 0,
    unpaidDayAction: UnpaidDayAction.NONE,
    createdAt: "2024-08-20T10:00:00Z",
    lastActiveAt: "2025-01-15T17:45:00Z",
  },
  {
    id: "rider-003",
    firstName: "Olumide",
    lastName: "Adeyemi",
    email: "o.adeyemi@email.com",
    phone: "+234 803 456 7890",
    avatarUrl: "https://i.pravatar.cc/80?img=12",
    role: UserRole.RIDER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE,
    riderId: "KR-2024-00789",
    assignedBikeId: "bike-034",
    fleetManagerId: "fm-002",
    dailyPaymentAmount: 3000,
    totalPaidToDate: 360000,
    paymentStreak: 12,
    repaymentRate: 91.7,
    hmoEnrolled: false,
    ownershipProgressMonths: 4,
    lastKnownLocation: { latitude: 6.335, longitude: 5.627 },
    accountBalance: 0,
    unpaidDays: 2,
    unpaidDayAction: UnpaidDayAction.FM_CALL,
    createdAt: "2024-09-10T09:00:00Z",
    lastActiveAt: "2025-01-15T16:20:00Z",
  },
  {
    id: "rider-004",
    firstName: "Ibrahim",
    lastName: "Musah",
    email: "i.musah@email.com",
    phone: "+234 804 567 8901",
    avatarUrl: "https://i.pravatar.cc/80?img=53",
    role: UserRole.RIDER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.SUSPENDED,
    riderId: "KR-2024-00234",
    assignedBikeId: null,
    fleetManagerId: "fm-002",
    dailyPaymentAmount: 3000,
    totalPaidToDate: 270000,
    paymentStreak: 0,
    repaymentRate: 62.5,
    hmoEnrolled: false,
    ownershipProgressMonths: 3,
    lastKnownLocation: null,
    accountBalance: -10500,
    unpaidDays: 5,
    unpaidDayAction: UnpaidDayAction.BIKE_RETRIEVAL,
    createdAt: "2024-06-01T07:00:00Z",
    lastActiveAt: "2025-01-10T12:00:00Z",
  },
  {
    id: "rider-005",
    firstName: "Chioma",
    lastName: "Eze",
    email: "c.eze@email.com",
    phone: "+234 805 678 9012",
    avatarUrl: "https://i.pravatar.cc/80?img=25",
    role: UserRole.RIDER,
    kycStatus: KycStatus.IN_REVIEW,
    status: RiderStatus.PENDING_ONBOARDING,
    riderId: "KR-2025-01001",
    assignedBikeId: null,
    fleetManagerId: "fm-003",
    dailyPaymentAmount: 3500,
    totalPaidToDate: 0,
    paymentStreak: 0,
    repaymentRate: 0,
    hmoEnrolled: false,
    ownershipProgressMonths: 0,
    lastKnownLocation: null,
    accountBalance: 0,
    unpaidDays: 0,
    unpaidDayAction: UnpaidDayAction.NONE,
    createdAt: "2025-01-14T14:00:00Z",
    lastActiveAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "rider-006",
    firstName: "Abdulahi",
    lastName: "Garba",
    email: "a.garba@email.com",
    phone: "+234 806 789 0123",
    avatarUrl: "https://i.pravatar.cc/80?img=15",
    role: UserRole.RIDER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE,
    riderId: "KR-2024-00345",
    assignedBikeId: "bike-045",
    fleetManagerId: "fm-003",
    dailyPaymentAmount: 3000,
    totalPaidToDate: 480000,
    paymentStreak: 30,
    repaymentRate: 99.1,
    hmoEnrolled: true,
    ownershipProgressMonths: 8,
    lastKnownLocation: { latitude: 7.4914, longitude: 3.9013 },
    accountBalance: 6000,
    unpaidDays: 0,
    unpaidDayAction: UnpaidDayAction.NONE,
    createdAt: "2024-05-20T08:00:00Z",
    lastActiveAt: "2025-01-15T19:00:00Z",
  },
  {
    id: "rider-007",
    firstName: "Blessing",
    lastName: "Okafor",
    email: "b.okafor@email.com",
    phone: "+234 807 890 1234",
    avatarUrl: "https://i.pravatar.cc/80?img=26",
    role: UserRole.RIDER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE,
    riderId: "KR-2024-00567",
    assignedBikeId: "bike-056",
    fleetManagerId: "fm-001",
    dailyPaymentAmount: 3500,
    totalPaidToDate: 560000,
    paymentStreak: 15,
    repaymentRate: 93.4,
    hmoEnrolled: true,
    ownershipProgressMonths: 5,
    lastKnownLocation: { latitude: 6.5955, longitude: 3.342 },
    accountBalance: 0,
    unpaidDays: 3,
    unpaidDayAction: UnpaidDayAction.FINAL_WARNING,
    createdAt: "2024-08-05T09:00:00Z",
    lastActiveAt: "2025-01-15T20:15:00Z",
  },
  {
    id: "rider-008",
    firstName: "Yusuf",
    lastName: "Bello",
    email: "y.bello@email.com",
    phone: "+234 808 901 2345",
    avatarUrl: "https://i.pravatar.cc/80?img=52",
    role: UserRole.RIDER,
    kycStatus: KycStatus.PENDING,
    status: RiderStatus.INACTIVE,
    riderId: "KR-2024-00678",
    assignedBikeId: null,
    fleetManagerId: "fm-004",
    dailyPaymentAmount: 3000,
    totalPaidToDate: 180000,
    paymentStreak: 0,
    repaymentRate: 75.0,
    hmoEnrolled: false,
    ownershipProgressMonths: 2,
    lastKnownLocation: { latitude: 9.0579, longitude: 7.4951 },
    accountBalance: 0,
    unpaidDays: 4,
    unpaidDayAction: UnpaidDayAction.SUSPENDED,
    createdAt: "2024-10-01T11:00:00Z",
    lastActiveAt: "2024-12-28T15:30:00Z",
  },
  {
    id: "rider-009",
    firstName: "Fatimah",
    lastName: "Ibrahim",
    email: "f.ibrahim@email.com",
    phone: "+234 809 012 3456",
    avatarUrl: "https://i.pravatar.cc/80?img=45",
    role: UserRole.RIDER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE,
    riderId: "KR-2024-00890",
    assignedBikeId: "bike-067",
    fleetManagerId: "fm-004",
    dailyPaymentAmount: 3500,
    totalPaidToDate: 420000,
    paymentStreak: 21,
    repaymentRate: 96.8,
    hmoEnrolled: true,
    ownershipProgressMonths: 4,
    lastKnownLocation: { latitude: 12.0022, longitude: 8.592 },
    accountBalance: 0,
    unpaidDays: 1,
    unpaidDayAction: UnpaidDayAction.SMS_WARNING,
    createdAt: "2024-09-15T08:30:00Z",
    lastActiveAt: "2025-01-15T18:00:00Z",
  },
  {
    id: "rider-010",
    firstName: "Emeka",
    lastName: "Nwachukwu",
    email: "e.nwachukwu@email.com",
    phone: "+234 810 123 4567",
    avatarUrl: "https://i.pravatar.cc/80?img=68",
    role: UserRole.RIDER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE,
    riderId: "KR-2024-00901",
    assignedBikeId: "bike-078",
    fleetManagerId: "fm-005",
    dailyPaymentAmount: 3500,
    totalPaidToDate: 700000,
    paymentStreak: 36,
    repaymentRate: 100.0,
    hmoEnrolled: true,
    ownershipProgressMonths: 10,
    lastKnownLocation: { latitude: 5.0124, longitude: 7.0123 },
    accountBalance: 10500,
    unpaidDays: 0,
    unpaidDayAction: UnpaidDayAction.NONE,
    createdAt: "2024-03-10T07:00:00Z",
    lastActiveAt: "2025-01-15T17:00:00Z",
  },
];

// ============================================================================
// FLEET MANAGERS
// ============================================================================

export const mockFleetManagers: FleetManager[] = [
  {
    id: "fm-001",
    firstName: "Tunde",
    lastName: "Bakare",
    email: "t.bakare@kowaride.com",
    phone: "+234 701 234 5678",
    avatarUrl: "",
    role: UserRole.FLEET_MANAGER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE as unknown as undefined,
    managerId: "FM-001",
    tier: PerformanceTier.PLATINUM,
    performanceScore: 96,
    totalBikesAssigned: 28,
    activeRiders: 27,
    portfolioRepaymentRate: 94.5,
    utilizationRate: 96.2,
    incidentCount30d: 1,
    monthlyFee: 84000,
    fleetOwnerId: "fo-001",
    createdAt: "2024-01-15T08:00:00Z",
    lastActiveAt: "2025-01-15T18:00:00Z",
  },
  {
    id: "fm-002",
    firstName: "Ngozi",
    lastName: "Anyawu",
    email: "n.anyawu@kowaride.com",
    phone: "+234 702 345 6789",
    avatarUrl: "",
    role: UserRole.FLEET_MANAGER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE as unknown as undefined,
    managerId: "FM-002",
    tier: PerformanceTier.GOLD,
    performanceScore: 88,
    totalBikesAssigned: 22,
    activeRiders: 20,
    portfolioRepaymentRate: 89.3,
    utilizationRate: 90.1,
    incidentCount30d: 3,
    monthlyFee: 66000,
    fleetOwnerId: "fo-001",
    createdAt: "2024-02-20T09:00:00Z",
    lastActiveAt: "2025-01-15T17:30:00Z",
  },
  {
    id: "fm-003",
    firstName: "Samuel",
    lastName: "Ogundimu",
    email: "s.ogundimu@kowaride.com",
    phone: "+234 703 456 7890",
    avatarUrl: "",
    role: UserRole.FLEET_MANAGER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE as unknown as undefined,
    managerId: "FM-003",
    tier: PerformanceTier.SILVER,
    performanceScore: 78,
    totalBikesAssigned: 18,
    activeRiders: 16,
    portfolioRepaymentRate: 82.1,
    utilizationRate: 84.5,
    incidentCount30d: 5,
    monthlyFee: 54000,
    fleetOwnerId: "fo-002",
    createdAt: "2024-04-10T10:00:00Z",
    lastActiveAt: "2025-01-15T16:45:00Z",
  },
  {
    id: "fm-004",
    firstName: "Amina",
    lastName: "Dangote",
    email: "a.dangote@kowaride.com",
    phone: "+234 704 567 8901",
    avatarUrl: "",
    role: UserRole.FLEET_MANAGER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE as unknown as undefined,
    managerId: "FM-004",
    tier: PerformanceTier.BRONZE,
    performanceScore: 65,
    totalBikesAssigned: 15,
    activeRiders: 12,
    portfolioRepaymentRate: 74.8,
    utilizationRate: 78.3,
    incidentCount30d: 8,
    monthlyFee: 45000,
    fleetOwnerId: "fo-002",
    createdAt: "2024-05-15T08:00:00Z",
    lastActiveAt: "2025-01-15T15:00:00Z",
  },
  {
    id: "fm-005",
    firstName: "David",
    lastName: "Olatunji",
    email: "d.olatunji@kowaride.com",
    phone: "+234 705 678 9012",
    avatarUrl: "",
    role: UserRole.FLEET_MANAGER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE as unknown as undefined,
    managerId: "FM-005",
    tier: PerformanceTier.PLATINUM,
    performanceScore: 94,
    totalBikesAssigned: 30,
    activeRiders: 29,
    portfolioRepaymentRate: 93.7,
    utilizationRate: 95.8,
    incidentCount30d: 2,
    monthlyFee: 90000,
    fleetOwnerId: "fo-003",
    createdAt: "2024-01-05T07:00:00Z",
    lastActiveAt: "2025-01-15T19:30:00Z",
  },
  {
    id: "fm-006",
    firstName: "Hauwa",
    lastName: "Kwaje",
    email: "h.kwaje@kowaride.com",
    phone: "+234 706 789 0123",
    avatarUrl: "",
    role: UserRole.FLEET_MANAGER,
    kycStatus: KycStatus.VERIFIED,
    status: RiderStatus.ACTIVE as unknown as undefined,
    managerId: "FM-006",
    tier: PerformanceTier.PROBATION,
    performanceScore: 45,
    totalBikesAssigned: 10,
    activeRiders: 7,
    portfolioRepaymentRate: 62.3,
    utilizationRate: 68.9,
    incidentCount30d: 12,
    monthlyFee: 30000,
    fleetOwnerId: "fo-003",
    createdAt: "2024-08-01T09:00:00Z",
    lastActiveAt: "2025-01-14T14:00:00Z",
  },
];

// ============================================================================
// FLEET OWNERS
// ============================================================================

export const mockFleetOwners: FleetOwner[] = [
  {
    id: "fo-001",
    firstName: "Chief",
    lastName: "Adeniyi",
    email: "c.adeniyi@kowaride.com",
    phone: "+234 901 234 5678",
    avatarUrl: "",
    role: UserRole.FLEET_OWNER,
    kycStatus: KycStatus.VERIFIED,
    createdAt: "2024-01-10T08:00:00Z",
    lastActiveAt: "2025-01-15T12:00:00Z",
    ownerId: "FO-001",
    totalBikes: 50,
    activeBikes: 47,
    totalRoi: 34.5,
    monthlyRoi: 4.2,
    pendingPayout: 2450000,
    totalEarnings: 34500000,
    bankDetails: {
      bankName: "GTBank",
      accountNumber: "0123456789",
      accountName: "Adeniyi Ventures Ltd",
    },
    avgActiveDaysPerWeek: 6.2,
  },
  {
    id: "fo-002",
    firstName: "Alhaji",
    lastName: "Mohammed",
    email: "a.mohammed@kowaride.com",
    phone: "+234 902 345 6789",
    avatarUrl: "",
    role: UserRole.FLEET_OWNER,
    kycStatus: KycStatus.VERIFIED,
    createdAt: "2024-03-20T09:00:00Z",
    lastActiveAt: "2025-01-15T10:30:00Z",
    ownerId: "FO-002",
    totalBikes: 33,
    activeBikes: 28,
    totalRoi: 28.7,
    monthlyRoi: 3.5,
    pendingPayout: 1680000,
    totalEarnings: 18200000,
    bankDetails: {
      bankName: "Access Bank",
      accountNumber: "0987654321",
      accountName: "Mohammed Logistics",
    },
    avgActiveDaysPerWeek: 5.8,
  },
  {
    id: "fo-003",
    firstName: "Dr.",
    lastName: "Okoro",
    email: "d.okoro@kowaride.com",
    phone: "+234 903 456 7890",
    avatarUrl: "",
    role: UserRole.FLEET_OWNER,
    kycStatus: KycStatus.VERIFIED,
    createdAt: "2024-01-05T07:00:00Z",
    lastActiveAt: "2025-01-15T11:00:00Z",
    ownerId: "FO-003",
    totalBikes: 40,
    activeBikes: 38,
    totalRoi: 31.2,
    monthlyRoi: 3.9,
    pendingPayout: 1950000,
    totalEarnings: 25600000,
    bankDetails: {
      bankName: "First Bank",
      accountNumber: "1122334455",
      accountName: "Okoro Fleet Services",
    },
    avgActiveDaysPerWeek: 6.5,
  },
  {
    id: "fo-004",
    firstName: "Mrs.",
    lastName: "Chukwu",
    email: "m.chukwu@kowaride.com",
    phone: "+234 904 567 8901",
    avatarUrl: "",
    role: UserRole.FLEET_OWNER,
    kycStatus: KycStatus.VERIFIED,
    createdAt: "2024-06-15T10:00:00Z",
    lastActiveAt: "2025-01-14T16:00:00Z",
    ownerId: "FO-004",
    totalBikes: 25,
    activeBikes: 22,
    totalRoi: 22.1,
    monthlyRoi: 2.8,
    pendingPayout: 980000,
    totalEarnings: 11200000,
    bankDetails: {
      bankName: "UBA",
      accountNumber: "2233445566",
      accountName: "Chukwu Investments",
    },
    avgActiveDaysPerWeek: 5.4,
  },
  {
    id: "fo-005",
    firstName: "Engr.",
    lastName: "Babatunde",
    email: "e.babatunde@kowaride.com",
    phone: "+234 905 678 9012",
    avatarUrl: "",
    role: UserRole.FLEET_OWNER,
    kycStatus: KycStatus.IN_REVIEW,
    createdAt: "2024-11-01T11:00:00Z",
    lastActiveAt: "2025-01-13T09:00:00Z",
    ownerId: "FO-005",
    totalBikes: 15,
    activeBikes: 13,
    totalRoi: 12.5,
    monthlyRoi: 3.1,
    pendingPayout: 560000,
    totalEarnings: 3750000,
    bankDetails: {
      bankName: "Zenith Bank",
      accountNumber: "3344556677",
      accountName: "Babatunde Engineering Ltd",
    },
    avgActiveDaysPerWeek: 6.0,
  },
];

// ============================================================================
// BIKE ASSETS
// ============================================================================

export const mockBikes: BikeAsset[] = [
  {
    id: "bike-012",
    assetId: "KR-BIKE-00112",
    makeModel: "Honda CG 125",
    year: 2023,
    color: "Red",
    plateNumber: "LAG-123-AB",
    vinNumber: "VNHGJ5678N1234567",
    status: AssetStatus.ACTIVE,
    assignedRiderId: "rider-001",
    fleetManagerId: "fm-001",
    fleetOwnerId: "fo-001",
    registeredAt: "2024-07-15T08:00:00Z",
    currentValue: 850000,
    purchasePrice: 1200000,
    odometerKm: 23456,
    lastGpsPing: { latitude: 6.5244, longitude: 3.3792, timestamp: "2025-01-15T18:30:00Z", speed: 45 },
    maintenanceCount: 3,
    lastMaintenanceDate: "2024-12-20T10:00:00Z",
    nextMaintenanceDate: "2025-03-20T10:00:00Z",
  },
  {
    id: "bike-023",
    assetId: "KR-BIKE-00234",
    makeModel: "Bajaj Boxer 150",
    year: 2023,
    color: "Black",
    plateNumber: "LAG-456-CD",
    vinNumber: "VNHGJ5678N2345678",
    status: AssetStatus.ACTIVE,
    assignedRiderId: "rider-002",
    fleetManagerId: "fm-001",
    fleetOwnerId: "fo-001",
    registeredAt: "2024-08-20T10:00:00Z",
    currentValue: 780000,
    purchasePrice: 950000,
    odometerKm: 18234,
    lastGpsPing: { latitude: 6.4541, longitude: 3.3947, timestamp: "2025-01-15T17:45:00Z", speed: 32 },
    maintenanceCount: 2,
    lastMaintenanceDate: "2024-11-15T09:00:00Z",
    nextMaintenanceDate: "2025-02-15T09:00:00Z",
  },
  {
    id: "bike-034",
    assetId: "KR-BIKE-00345",
    makeModel: "TVS Apache 200",
    year: 2024,
    color: "Blue",
    plateNumber: "ABJ-789-EF",
    vinNumber: "VNHGJ5678N3456789",
    status: AssetStatus.ACTIVE,
    assignedRiderId: "rider-003",
    fleetManagerId: "fm-002",
    fleetOwnerId: "fo-002",
    registeredAt: "2024-09-10T09:00:00Z",
    currentValue: 1100000,
    purchasePrice: 1450000,
    odometerKm: 12345,
    lastGpsPing: { latitude: 6.335, longitude: 5.627, timestamp: "2025-01-15T16:20:00Z", speed: 55 },
    maintenanceCount: 1,
    lastMaintenanceDate: "2024-12-01T10:00:00Z",
    nextMaintenanceDate: "2025-03-01T10:00:00Z",
  },
  {
    id: "bike-045",
    assetId: "KR-BIKE-00456",
    makeModel: "Honda CG 125",
    year: 2023,
    color: "Green",
    plateNumber: "IBD-012-GH",
    vinNumber: "VNHGJ5678N4567890",
    status: AssetStatus.IN_MAINTENANCE,
    assignedRiderId: null,
    fleetManagerId: "fm-003",
    fleetOwnerId: "fo-002",
    registeredAt: "2024-05-20T08:00:00Z",
    currentValue: 720000,
    purchasePrice: 1200000,
    odometerKm: 34567,
    lastGpsPing: null,
    maintenanceCount: 7,
    lastMaintenanceDate: "2025-01-13T10:00:00Z",
    nextMaintenanceDate: "2025-01-20T10:00:00Z",
  },
  {
    id: "bike-056",
    assetId: "KR-BIKE-00567",
    makeModel: "Bajaj Pulsar 150",
    year: 2024,
    color: "Silver",
    plateNumber: "LAG-345-IJ",
    vinNumber: "VNHGJ5678N5678901",
    status: AssetStatus.ACTIVE,
    assignedRiderId: "rider-007",
    fleetManagerId: "fm-001",
    fleetOwnerId: "fo-001",
    registeredAt: "2024-08-05T09:00:00Z",
    currentValue: 920000,
    purchasePrice: 1100000,
    odometerKm: 15678,
    lastGpsPing: { latitude: 6.5955, longitude: 3.342, timestamp: "2025-01-15T20:15:00Z", speed: 28 },
    maintenanceCount: 2,
    lastMaintenanceDate: "2024-12-10T11:00:00Z",
    nextMaintenanceDate: "2025-03-10T11:00:00Z",
  },
  {
    id: "bike-067",
    assetId: "KR-BIKE-00678",
    makeModel: "Kymco K-Piper 125",
    year: 2023,
    color: "White",
    plateNumber: "KAD-678-KL",
    vinNumber: "VNHGJ5678N6789012",
    status: AssetStatus.ACTIVE,
    assignedRiderId: "rider-009",
    fleetManagerId: "fm-004",
    fleetOwnerId: "fo-003",
    registeredAt: "2024-09-15T08:30:00Z",
    currentValue: 680000,
    purchasePrice: 900000,
    odometerKm: 21098,
    lastGpsPing: { latitude: 12.0022, longitude: 8.592, timestamp: "2025-01-15T18:00:00Z", speed: 40 },
    maintenanceCount: 4,
    lastMaintenanceDate: "2025-01-05T10:00:00Z",
    nextMaintenanceDate: "2025-02-05T10:00:00Z",
  },
  {
    id: "bike-078",
    assetId: "KR-BIKE-00789",
    makeModel: "Honda CB125",
    year: 2023,
    color: "Black",
    plateNumber: "PH-901-MN",
    vinNumber: "VNHGJ5678N7890123",
    status: AssetStatus.ACTIVE,
    assignedRiderId: "rider-010",
    fleetManagerId: "fm-005",
    fleetOwnerId: "fo-003",
    registeredAt: "2024-03-10T07:00:00Z",
    currentValue: 750000,
    purchasePrice: 1150000,
    odometerKm: 40123,
    lastGpsPing: { latitude: 5.0124, longitude: 7.0123, timestamp: "2025-01-15T17:00:00Z", speed: 35 },
    maintenanceCount: 5,
    lastMaintenanceDate: "2024-12-28T09:00:00Z",
    nextMaintenanceDate: "2025-03-28T09:00:00Z",
  },
  {
    id: "bike-089",
    assetId: "KR-BIKE-00890",
    makeModel: "Suzuki GS125",
    year: 2022,
    color: "Red",
    plateNumber: "LAG-234-OP",
    vinNumber: "VNHGJ5678N8901234",
    status: AssetStatus.REPORTED_STOLEN,
    assignedRiderId: null,
    fleetManagerId: "fm-002",
    fleetOwnerId: "fo-001",
    registeredAt: "2024-04-01T08:00:00Z",
    currentValue: 500000,
    purchasePrice: 1000000,
    odometerKm: 28901,
    lastGpsPing: { latitude: 6.4281, longitude: 3.4219, timestamp: "2025-01-08T22:30:00Z", speed: 0 },
    maintenanceCount: 3,
    lastMaintenanceDate: "2024-11-20T10:00:00Z",
    nextMaintenanceDate: null,
  },
];

// ============================================================================
// TRANSACTIONS
// ============================================================================

export const mockTransactions: Transaction[] = [
  {
    id: "txn-001",
    reference: "TXN-20250115-AB12CD",
    type: TransactionType.DAILY_PAYMENT,
    status: TransactionStatus.COMPLETED,
    amount: 3500,
    description: "Daily payment - Chukwuemeka Okonkwo",
    initiatedBy: "rider-001",
    receivedBy: "system",
    createdAt: "2025-01-15T23:45:00Z",
    completedAt: "2025-01-15T23:45:12Z",
    metadata: { riderId: "rider-001", bikeId: "bike-012" },
  },
  {
    id: "txn-002",
    reference: "TXN-20250115-EF34GH",
    type: TransactionType.DAILY_PAYMENT,
    status: TransactionStatus.COMPLETED,
    amount: 3500,
    description: "Daily payment - Aishat Abubakar",
    initiatedBy: "rider-002",
    receivedBy: "system",
    createdAt: "2025-01-15T22:30:00Z",
    completedAt: "2025-01-15T22:30:08Z",
    metadata: { riderId: "rider-002", bikeId: "bike-023" },
  },
  {
    id: "txn-003",
    reference: "TXN-20250114-IJ56KL",
    type: TransactionType.OWNER_PAYOUT,
    status: TransactionStatus.COMPLETED,
    amount: 2450000,
    description: "Weekly payout - Chief Adeniyi (FO-001)",
    initiatedBy: "system",
    receivedBy: "fo-001",
    createdAt: "2025-01-14T02:00:00Z",
    completedAt: "2025-01-14T02:15:34Z",
    metadata: { allocationBatchId: "batch-001" },
  },
  {
    id: "txn-004",
    reference: "TXN-20250114-MN78OP",
    type: TransactionType.MAINTENANCE_ALLOCATION,
    status: TransactionStatus.COMPLETED,
    amount: 75000,
    description: "Bike KR-BIKE-00456 engine overhaul",
    initiatedBy: "system",
    receivedBy: "vendor-maint-001",
    createdAt: "2025-01-14T10:00:00Z",
    completedAt: "2025-01-14T10:05:22Z",
    metadata: { bikeId: "bike-045" },
  },
  {
    id: "txn-005",
    reference: "TXN-20250113-QR90ST",
    type: TransactionType.MANAGER_FEE,
    status: TransactionStatus.PROCESSING,
    amount: 84000,
    description: "Monthly manager fee - Tunde Bakare (FM-001)",
    initiatedBy: "system",
    receivedBy: "fm-001",
    createdAt: "2025-01-13T00:00:00Z",
    completedAt: null,
    metadata: { allocationBatchId: "batch-002" },
  },
  {
    id: "txn-006",
    reference: "TXN-20250113-UV12WX",
    type: TransactionType.BONUS,
    status: TransactionStatus.COMPLETED,
    amount: 7000,
    description: "Streak bonus - Abdulahi Garba (12-month streak)",
    initiatedBy: "system",
    receivedBy: "rider-006",
    createdAt: "2025-01-13T08:00:00Z",
    completedAt: "2025-01-13T08:00:15Z",
    metadata: { riderId: "rider-006" },
  },
  {
    id: "txn-007",
    reference: "TXN-20250112-YZ34AB",
    type: TransactionType.PENALTY,
    status: TransactionStatus.COMPLETED,
    amount: 5000,
    description: "Late payment penalty - Ibrahim Musah",
    initiatedBy: "system",
    receivedBy: "system",
    createdAt: "2025-01-12T00:05:00Z",
    completedAt: "2025-01-12T00:05:10Z",
    metadata: { riderId: "rider-004" },
  },
  {
    id: "txn-008",
    reference: "TXN-20250111-CD56EF",
    type: TransactionType.COMPANY_REVENUE,
    status: TransactionStatus.COMPLETED,
    amount: 1250000,
    description: "Daily platform revenue allocation",
    initiatedBy: "system",
    receivedBy: "company",
    createdAt: "2025-01-11T23:59:00Z",
    completedAt: "2025-01-11T23:59:45Z",
    metadata: { allocationBatchId: "batch-003" },
  },
  {
    id: "txn-009",
    reference: "TXN-20250110-GH78IJ",
    type: TransactionType.DAILY_PAYMENT,
    status: TransactionStatus.FAILED,
    amount: 3000,
    description: "Daily payment FAILED - Yusuf Bello (insufficient funds)",
    initiatedBy: "rider-008",
    receivedBy: "system",
    createdAt: "2025-01-10T23:30:00Z",
    completedAt: null,
    metadata: { riderId: "rider-008", bikeId: "bike-067" },
  },
  {
    id: "txn-010",
    reference: "TXN-20250109-KL90MN",
    type: TransactionType.OWNER_PAYOUT,
    status: TransactionStatus.FLAGGED,
    amount: 1680000,
    description: "Weekly payout FLAGGED - Alhaji Mohammed (utilization below threshold)",
    initiatedBy: "system",
    receivedBy: "fo-002",
    createdAt: "2025-01-09T02:00:00Z",
    completedAt: null,
    metadata: { allocationBatchId: "batch-004" },
  },
  {
    id: "txn-011",
    reference: "TXN-20250108-OP12QR",
    type: TransactionType.HMO_PREMIUM,
    status: TransactionStatus.COMPLETED,
    amount: 15000,
    description: "Monthly HMO premium deduction - Tunde Bakare's fleet",
    initiatedBy: "system",
    receivedBy: "hmo-provider-001",
    createdAt: "2025-01-08T06:00:00Z",
    completedAt: "2025-01-08T06:02:30Z",
    metadata: { fleetManagerId: "fm-001" },
  },
  {
    id: "txn-012",
    reference: "TXN-20250107-ST34UV",
    type: TransactionType.RESERVE_FUND,
    status: TransactionStatus.COMPLETED,
    amount: 350000,
    description: "Daily reserve fund allocation",
    initiatedBy: "system",
    receivedBy: "reserve",
    createdAt: "2025-01-07T23:59:00Z",
    completedAt: "2025-01-07T23:59:20Z",
    metadata: { allocationBatchId: "batch-005" },
  },
];

// ============================================================================
// PAYOUT SUMMARIES
// ============================================================================

export const mockPayouts: PayoutSummary[] = [
  {
    id: "po-001",
    ownerId: "fo-001",
    ownerName: "Chief Adeniyi",
    amount: 2450000,
    activeDays: 42,
    periodStart: "2025-01-06",
    periodEnd: "2025-01-12",
    status: TransactionStatus.COMPLETED,
    processedAt: "2025-01-14T02:15:34Z",
  },
  {
    id: "po-002",
    ownerId: "fo-002",
    ownerName: "Alhaji Mohammed",
    amount: 1680000,
    activeDays: 28,
    periodStart: "2025-01-06",
    periodEnd: "2025-01-12",
    status: TransactionStatus.FLAGGED,
    processedAt: null,
  },
  {
    id: "po-003",
    ownerId: "fo-003",
    ownerName: "Dr. Okoro",
    amount: 1950000,
    activeDays: 38,
    periodStart: "2025-01-06",
    periodEnd: "2025-01-12",
    status: TransactionStatus.PENDING,
    processedAt: null,
  },
  {
    id: "po-004",
    ownerId: "fo-004",
    ownerName: "Mrs. Chukwu",
    amount: 980000,
    activeDays: 22,
    periodStart: "2025-01-06",
    periodEnd: "2025-01-12",
    status: TransactionStatus.COMPLETED,
    processedAt: "2025-01-14T02:30:00Z",
  },
  {
    id: "po-005",
    ownerId: "fo-005",
    ownerName: "Engr. Babatunde",
    amount: 560000,
    activeDays: 12,
    periodStart: "2025-01-06",
    periodEnd: "2025-01-12",
    status: TransactionStatus.PROCESSING,
    processedAt: null,
  },
];

// ============================================================================
// SYSTEM ALERTS
// ============================================================================

export const mockAlerts: SystemAlert[] = [
  {
    id: "alert-001",
    severity: AlertSeverity.CRITICAL,
    title: "Stolen Asset - KR-BIKE-00890",
    description: "GPS signal lost for bike KR-BIKE-00890 registered to Fleet Manager Ngozi Anyawu. Last ping received Jan 8 at Ikeja, Lagos. Police report filed: REF-LPD-2025-0456.",
    entityType: "ASSET",
    entityId: "bike-089",
    isAcknowledged: false,
    isResolved: false,
    recommendedAction: "Coordinate with insurance provider for total loss claim. Reassign rider to available asset.",
    createdAt: "2025-01-08T23:00:00Z",
  },
  {
    id: "alert-002",
    severity: AlertSeverity.CRITICAL,
    title: "Payment Fraud Pattern Detected",
    description: "Rider Ibrahim Musah (KR-2024-00234) flagged for potential fraud: GPS mismatch with claimed location, 3 consecutive payment failures, and 14 days of communication silence.",
    entityType: "RIDER",
    entityId: "rider-004",
    isAcknowledged: true,
    isResolved: false,
    recommendedAction: "Suspend account pending investigation. Contact emergency contact on file. Initiate asset recovery protocol.",
    createdAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "alert-003",
    severity: AlertSeverity.ERROR,
    title: "Fleet Manager Below Performance Threshold",
    description: "Hauwa Kwaje (FM-006) performance score dropped to 45. Portfolio repayment rate at 62.3% with 12 incidents in the last 30 days. Automatic downgrade to Probation tier triggered.",
    entityType: "FLEET_MANAGER",
    entityId: "fm-006",
    isAcknowledged: false,
    isResolved: false,
    recommendedAction: "Schedule performance review meeting. Consider asset reallocation if no improvement in 14 days.",
    createdAt: "2025-01-14T10:00:00Z",
  },
  {
    id: "alert-004",
    severity: AlertSeverity.WARNING,
    title: "Payout Blocked - Utilization Below Threshold",
    description: "Alhaji Mohammed (FO-002) weekly payout of ₦1,680,000 blocked. Fleet utilization at 4.2 days/week, below the 5-day minimum threshold.",
    entityType: "FINANCIAL",
    entityId: "fo-002",
    isAcknowledged: true,
    isResolved: false,
    recommendedAction: "Notify fleet owner. Work with assigned managers to improve utilization. Payout will release when threshold met.",
    createdAt: "2025-01-09T02:30:00Z",
  },
  {
    id: "alert-005",
    severity: AlertSeverity.WARNING,
    title: "Scheduled Maintenance Overdue",
    description: "5 bikes are past their scheduled maintenance dates. KR-BIKE-00112, KR-BIKE-00234, KR-BIKE-00345, KR-BIKE-00678, and KR-BIKE-00789 require attention.",
    entityType: "ASSET",
    entityId: "system",
    isAcknowledged: false,
    isResolved: false,
    recommendedAction: "Coordinate with maintenance vendors. Prioritize bikes with higher mileage for immediate servicing.",
    createdAt: "2025-01-15T06:00:00Z",
  },
  {
    id: "alert-006",
    severity: AlertSeverity.INFO,
    title: "New Rider Onboarding Batch",
    description: "12 new riders have completed KYC verification and are pending fleet assignment. Contact the operations team for allocation.",
    entityType: "RIDER",
    entityId: "system",
    isAcknowledged: false,
    isResolved: false,
    recommendedAction: "Review rider profiles and assign to fleet managers with available capacity.",
    createdAt: "2025-01-15T09:00:00Z",
  },
  {
    id: "alert-007",
    severity: AlertSeverity.WARNING,
    title: "Payment Gateway Latency Spike",
    description: "Average payment processing time increased to 4.2s (SLA: <2s). 23 transactions affected in the last hour. Root cause: upstream provider degradation.",
    entityType: "SYSTEM",
    entityId: "payment-gateway",
    isAcknowledged: true,
    isResolved: true,
    recommendedAction: "Monitor. Circuit breaker active. Failover to secondary provider initiated.",
    createdAt: "2025-01-15T14:30:00Z",
  },
  {
    id: "alert-008",
    severity: AlertSeverity.INFO,
    title: "Monthly Compliance Report Ready",
    description: "January 2025 compliance report has been generated. Available for review and submission to regulatory bodies.",
    entityType: "SYSTEM",
    entityId: "compliance-report",
    isAcknowledged: false,
    isResolved: false,
    recommendedAction: "Review report and submit to CBN and NAICOM before January 31 deadline.",
    createdAt: "2025-01-15T00:00:00Z",
  },
];

// ============================================================================
// RISK ASSESSMENTS
// ============================================================================

export const mockRiskAssessments: RiskAssessment[] = [
  {
    entityId: "rider-004",
    entityType: "RIDER",
    riskLevel: RiskLevel.CRITICAL,
    riskScore: 92,
    factors: [
      { name: "Payment History", score: 95, value: "62.5% repayment", isAcceptable: false },
      { name: "GPS Compliance", score: 88, value: "Last ping 5 days ago", isAcceptable: false },
      { name: "Communication", score: 90, value: "14 days silent", isAcceptable: false },
      { name: "Account Balance", score: 70, value: "-₦10,500", isAcceptable: false },
      { name: "Incident Record", score: 40, value: "0 incidents", isAcceptable: true },
    ],
    assessedAt: "2025-01-15T08:00:00Z",
  },
  {
    entityId: "fm-006",
    entityType: "FLEET_MANAGER",
    riskLevel: RiskLevel.HIGH,
    riskScore: 78,
    factors: [
      { name: "Portfolio Repayment", score: 82, value: "62.3%", isAcceptable: false },
      { name: "Utilization Rate", score: 70, value: "68.9%", isAcceptable: false },
      { name: "Incident Frequency", score: 85, value: "12 in 30 days", isAcceptable: false },
      { name: "Rider Retention", score: 75, value: "70% retention", isAcceptable: false },
      { name: "Performance Score", score: 78, value: "45/100", isAcceptable: false },
    ],
    assessedAt: "2025-01-14T10:00:00Z",
  },
  {
    entityId: "fo-002",
    entityType: "FLEET_OWNER",
    riskLevel: RiskLevel.MEDIUM,
    riskScore: 45,
    factors: [
      { name: "Utilization Rate", score: 55, value: "5.8 days/week", isAcceptable: true },
      { name: "Payout Status", score: 60, value: "1 flagged payout", isAcceptable: false },
      { name: "Asset Condition", score: 35, value: "85% active", isAcceptable: true },
      { name: "Financial Health", score: 40, value: "28.7% ROI", isAcceptable: true },
    ],
    assessedAt: "2025-01-15T06:00:00Z",
  },
  {
    entityId: "rider-008",
    entityType: "RIDER",
    riskLevel: RiskLevel.MEDIUM,
    riskScore: 55,
    factors: [
      { name: "Payment History", score: 60, value: "75% repayment", isAcceptable: false },
      { name: "Activity Level", score: 65, value: "Inactive 18 days", isAcceptable: false },
      { name: "GPS Compliance", score: 40, value: "No recent pings", isAcceptable: false },
      { name: "Account Balance", score: 30, value: "₦0", isAcceptable: true },
    ],
    assessedAt: "2025-01-15T12:00:00Z",
  },
];

// ============================================================================
// AUDIT LOGS
// ============================================================================

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: "audit-001",
    timestamp: "2025-01-15T18:30:00Z",
    actorId: "admin-001",
    actorName: "Super Admin",
    actorRole: UserRole.SUPER_ADMIN,
    action: "SUSPEND_RIDER",
    category: "ENFORCEMENT",
    targetEntity: "RIDER",
    targetId: "rider-004",
    details: "Suspended rider Ibrahim Musah (KR-2024-00234) for suspected fraud. Reason: GPS mismatch + payment failure + communication silence. Reference: Alert alert-002.",
    ipAddress: "192.168.1.100",
    previousEntryHash: "a1b2c3d4e5f6",
  },
  {
    id: "audit-002",
    timestamp: "2025-01-15T14:00:00Z",
    actorId: "system",
    actorName: "System",
    actorRole: UserRole.ADMIN,
    action: "TIER_DOWNGRADE",
    category: "OPERATIONS",
    targetEntity: "FLEET_MANAGER",
    targetId: "fm-006",
    details: "Automatic tier downgrade: Hauwa Kwaje (FM-006) moved from BRONZE to PROBATION. Performance score: 45. Trigger: weekly assessment cycle.",
    ipAddress: "system",
    previousEntryHash: "f6e5d4c3b2a1",
  },
  {
    id: "audit-003",
    timestamp: "2025-01-15T10:00:00Z",
    actorId: "admin-002",
    actorName: "Operations Lead",
    actorRole: UserRole.ADMIN,
    action: "OVERRIDE_PAYOUT",
    category: "FINANCIAL",
    targetEntity: "FLEET_OWNER",
    targetId: "fo-002",
    details: "Approved payout override for Alhaji Mohammed (FO-002) pending utilization review. Amount: ₦1,680,000. Dual approval: admin-001 + admin-002.",
    ipAddress: "192.168.1.101",
    previousEntryHash: "1a2b3c4d5e6f",
  },
  {
    id: "audit-004",
    timestamp: "2025-01-14T16:00:00Z",
    actorId: "admin-001",
    actorName: "Super Admin",
    actorRole: UserRole.SUPER_ADMIN,
    action: "UPDATE_CONFIG",
    category: "CONFIG",
    targetEntity: "SYSTEM_CONFIG",
    targetId: "daily_payment_deadline",
    details: "Changed daily payment deadline from 22:00 to 23:59 WAT. Reason: Align with rider feedback about evening collections.",
    ipAddress: "192.168.1.100",
    previousEntryHash: "6f5e4d3c2b1a",
  },
  {
    id: "audit-005",
    timestamp: "2025-01-14T09:00:00Z",
    actorId: "system",
    actorName: "System",
    actorRole: UserRole.ADMIN,
    action: "ALLOCATION_BATCH_COMPLETE",
    category: "FINANCIAL",
    targetEntity: "ALLOCATION_BATCH",
    targetId: "batch-003",
    details: "Daily allocation batch processed. Total collected: ₦11,247,500. Splits: Company ₦4,499,000 | Maintenance ₦1,124,750 | HMO ₦787,325 | Reserve ₦1,687,125 | Owners ₦2,249,500 | Managers ₦899,800.",
    ipAddress: "system",
    previousEntryHash: "c3d4e5f6a7b8",
  },
  {
    id: "audit-006",
    timestamp: "2025-01-13T11:00:00Z",
    actorId: "admin-003",
    actorName: "Compliance Officer",
    actorRole: UserRole.COMPLIANCE_OFFICER,
    action: "EXPORT_AUDIT_REPORT",
    category: "COMPLIANCE",
    targetEntity: "SYSTEM",
    targetId: "report-jan-2025",
    details: "Exported January 2025 compliance audit report. Format: PDF. Pages: 247. Records: 1,234.",
    ipAddress: "192.168.1.102",
    previousEntryHash: "b8a7f6e5d4c3",
  },
  {
    id: "audit-007",
    timestamp: "2025-01-12T15:00:00Z",
    actorId: "system",
    actorName: "System",
    actorRole: UserRole.ADMIN,
    action: "AUTO_ASSIGN_BIKE",
    category: "OPERATIONS",
    targetEntity: "RIDER",
    targetId: "rider-005",
    details: "Auto-assigned bike KR-BIKE-00901 to new rider Chioma Eze (KR-2025-01001) under Fleet Manager Samuel Ogundimu (FM-003).",
    ipAddress: "system",
    previousEntryHash: "d4c3b2a1f6e5",
  },
];

// ============================================================================
// CHART DATA
// ============================================================================

/** Revenue trend data for the last 12 months */
export const revenueChartData: ChartDataPoint[] = [
  { label: "Feb", value: 98, secondaryValue: 85 },
  { label: "Mar", value: 105, secondaryValue: 92 },
  { label: "Apr", value: 112, secondaryValue: 98 },
  { label: "May", value: 108, secondaryValue: 95 },
  { label: "Jun", value: 118, secondaryValue: 102 },
  { label: "Jul", value: 125, secondaryValue: 110 },
  { label: "Aug", value: 130, secondaryValue: 115 },
  { label: "Sep", value: 128, secondaryValue: 112 },
  { label: "Oct", value: 135, secondaryValue: 118 },
  { label: "Nov", value: 140, secondaryValue: 122 },
  { label: "Dec", value: 145, secondaryValue: 128 },
  { label: "Jan", value: 148, secondaryValue: 130 },
];

/** Daily collection rate data for the current week */
export const collectionChartData: ChartDataPoint[] = [
  { label: "Mon", value: 89, secondaryValue: 92 },
  { label: "Tue", value: 91, secondaryValue: 90 },
  { label: "Wed", value: 87, secondaryValue: 88 },
  { label: "Thu", value: 93, secondaryValue: 94 },
  { label: "Fri", value: 95, secondaryValue: 91 },
  { label: "Sat", value: 88, secondaryValue: 86 },
  { label: "Sun", value: 82, secondaryValue: 80 },
];

/** Fleet utilization data by manager */
export const utilizationChartData: ChartDataPoint[] = [
  { label: "Tunde B.", value: 96 },
  { label: "Ngozi A.", value: 90 },
  { label: "Samuel O.", value: 85 },
  { label: "Amina D.", value: 78 },
  { label: "David O.", value: 96 },
  { label: "Hauwa K.", value: 69 },
];

/** Rider status distribution for donut chart */
export const riderStatusData: ChartDataPoint[] = [
  { label: "Active", value: 3214 },
  { label: "Inactive", value: 289 },
  { label: "Suspended", value: 67 },
  { label: "Pending", value: 156 },
  { label: "Terminated", value: 121 },
];

/** Risk distribution data */
export const riskDistributionData: ChartDataPoint[] = [
  { label: "Low", value: 2890 },
  { label: "Medium", value: 612 },
  { label: "High", value: 234 },
  { label: "Critical", value: 111 },
];

// ============================================================================
// RECENT ACTIVITY
// ============================================================================

export const mockActivityFeed: ActivityItem[] = [
  {
    id: "act-001",
    type: "PAYMENT",
    title: "Daily Collection Batch Complete",
    description: "₦4,872,500 collected from 1,392 riders. Collection rate: 87.3%.",
    timestamp: "2025-01-15T23:59:00Z",
    relativeTime: "12 minutes ago",
    requiresAttention: false,
  },
  {
    id: "act-002",
    type: "ALERT",
    title: "Critical: Stolen Asset Report",
    description: "Bike KR-BIKE-00890 reported stolen. GPS last pinged at Ikeja, Lagos.",
    timestamp: "2025-01-15T23:00:00Z",
    relativeTime: "1 hour ago",
    requiresAttention: true,
  },
  {
    id: "act-003",
    type: "RIDER",
    title: "New Rider Onboarded",
    description: "Chioma Eze (KR-2025-01001) completed KYC verification.",
    timestamp: "2025-01-15T22:30:00Z",
    relativeTime: "2 hours ago",
    requiresAttention: false,
  },
  {
    id: "act-004",
    type: "FINANCIAL",
    title: "Payout Processed",
    description: "₦2,450,000 weekly payout to Chief Adeniyi (FO-001) completed.",
    timestamp: "2025-01-15T14:15:00Z",
    relativeTime: "10 hours ago",
    requiresAttention: false,
  },
  {
    id: "act-005",
    type: "FLEET",
    title: "Fleet Manager Downgraded",
    description: "Hauwa Kwaje (FM-006) automatically downgraded to Probation tier.",
    timestamp: "2025-01-15T10:00:00Z",
    relativeTime: "14 hours ago",
    requiresAttention: true,
  },
  {
    id: "act-006",
    type: "SYSTEM",
    title: "System Maintenance Scheduled",
    description: "Database maintenance window: Jan 16, 02:00-04:00 WAT.",
    timestamp: "2025-01-15T08:00:00Z",
    relativeTime: "16 hours ago",
    requiresAttention: false,
  },
  {
    id: "act-007",
    type: "ALERT",
    title: "Payment Fraud Detected",
    description: "Rider Ibrahim Musah flagged for suspicious activity pattern.",
    timestamp: "2025-01-14T20:00:00Z",
    relativeTime: "1 day ago",
    requiresAttention: true,
  },
  {
    id: "act-008",
    type: "FINANCIAL",
    title: "Payout Flagged",
    description: "Alhaji Mohammed payout blocked due to low utilization.",
    timestamp: "2025-01-14T09:30:00Z",
    relativeTime: "1 day ago",
    requiresAttention: true,
  },
];

// ============================================================================
// ALLOCATION BREAKDOWN (SAMPLE)
// ============================================================================

export const mockAllocationBreakdown: AllocationBreakdown = {
  companyRevenue: 1600,
  maintenanceFund: 400,
  hmoPremium: 280,
  reserveFund: 600,
  ownerPayout: 420,
  managerFee: 200,
  totalDailyPayment: 3500,
};

// ============================================================================
// SYSTEM CONFIGURATION
// ============================================================================

export const mockSystemConfigs: SystemConfig[] = [
  {
    key: "daily_payment_deadline",
    label: "Daily Payment Deadline",
    description: "Time by which all riders must complete their daily payment (WAT).",
    value: "23:59",
    type: "STRING",
    category: "FINANCIAL",
    isEditable: true,
    lastModifiedAt: "2025-01-14T16:00:00Z",
    lastModifiedBy: "Super Admin",
  },
  {
    key: "grace_period_hours",
    label: "Payment Grace Period",
    description: "Number of hours after deadline before penalty is applied.",
    value: 24,
    type: "NUMBER",
    category: "FINANCIAL",
    isEditable: true,
    lastModifiedAt: "2024-12-01T10:00:00Z",
    lastModifiedBy: "Super Admin",
  },
  {
    key: "streak_bonus_threshold",
    label: "Streak Bonus Threshold",
    description: "Number of consecutive on-time payments required for streak bonus.",
    value: 6,
    type: "NUMBER",
    category: "FINANCIAL",
    isEditable: true,
    lastModifiedAt: "2024-10-15T09:00:00Z",
    lastModifiedBy: "Operations Lead",
  },
  {
    key: "streak_bonus_amount",
    label: "Streak Bonus Amount (₦)",
    description: "Bonus amount awarded when streak threshold is reached.",
    value: 7000,
    type: "NUMBER",
    category: "FINANCIAL",
    isEditable: true,
    lastModifiedAt: "2024-10-15T09:00:00Z",
    lastModifiedBy: "Operations Lead",
  },
  {
    key: "min_utilization_days",
    label: "Minimum Utilization Days",
    description: "Minimum active days per week required for owner payout eligibility.",
    value: 5,
    type: "NUMBER",
    category: "FINANCIAL",
    isEditable: true,
    lastModifiedAt: "2024-08-20T11:00:00Z",
    lastModifiedBy: "Super Admin",
  },
  {
    key: "max_bikes_per_manager",
    label: "Max Bikes per Manager",
    description: "Maximum number of bikes that can be assigned to a single fleet manager.",
    value: 30,
    type: "NUMBER",
    category: "OPERATIONS",
    isEditable: true,
    lastModifiedAt: "2024-07-01T08:00:00Z",
    lastModifiedBy: "Super Admin",
  },
  {
    key: "ownership_unlock_months",
    label: "Ownership Pathway Duration",
    description: "Number of months of perfect repayment required to unlock bike ownership.",
    value: 18,
    type: "NUMBER",
    category: "OPERATIONS",
    isEditable: true,
    lastModifiedAt: "2024-06-15T10:00:00Z",
    lastModifiedBy: "Super Admin",
  },
  {
    key: "gps_ping_interval_sec",
    label: "GPS Ping Interval (seconds)",
    description: "Frequency at which bike GPS devices send location updates.",
    value: 60,
    type: "NUMBER",
    category: "OPERATIONS",
    isEditable: false,
    lastModifiedAt: "2024-05-01T07:00:00Z",
    lastModifiedBy: "System",
  },
  {
    key: "enable_sms_notifications",
    label: "Enable SMS Notifications",
    description: "Master toggle for SMS-based payment reminders and alerts.",
    value: true,
    type: "BOOLEAN",
    category: "NOTIFICATION",
    isEditable: true,
    lastModifiedAt: "2025-01-10T14:00:00Z",
    lastModifiedBy: "Operations Lead",
  },
  {
    key: "payment_reminder_hours",
    label: "Payment Reminder Timing",
    description: "Hours before deadline to send payment reminder SMS.",
    value: 3,
    type: "NUMBER",
    category: "NOTIFICATION",
    isEditable: true,
    lastModifiedAt: "2024-11-20T09:00:00Z",
    lastModifiedBy: "Operations Lead",
  },
  {
    key: "session_timeout_minutes",
    label: "Session Timeout (minutes)",
    description: "Automatic session logout after inactivity period.",
    value: 30,
    type: "NUMBER",
    category: "SECURITY",
    isEditable: true,
    lastModifiedAt: "2024-09-01T11:00:00Z",
    lastModifiedBy: "Super Admin",
  },
  {
    key: "max_concurrent_sessions",
    label: "Max Concurrent Sessions",
    description: "Maximum number of simultaneous active sessions per user.",
    value: 2,
    type: "NUMBER",
    category: "SECURITY",
    isEditable: true,
    lastModifiedAt: "2024-09-01T11:00:00Z",
    lastModifiedBy: "Super Admin",
  },
];
