/**
 * ============================================================================
 * KOWA RIDE - SUPERADMIN DASHBOARD
 * Drizzle Schema — Risk & Compliance (Alerts, Assessments, Factors)
 * ============================================================================
 *
 * System alerts generated by the risk engine, risk assessments with
 * factor breakdown, and audit log entries with hash chaining.
 *
 * @module db/schema/risk
 * @version 3.0.0 (Drizzle ORM)
 * ============================================================================
 */

import {
  pgTable,
  text,
  integer,
  boolean,
  timestamp,
  index,
} from "drizzle-orm/pg-core";
import { createId } from "@paralleldrive/cuid2";
import { relations } from "drizzle-orm";
import {
  riskLevelEnum,
  alertSeverityEnum,
  alertEntityTypeEnum,
  riskEntityTypeEnum,
  auditCategoryEnum,
  userRoleEnum,
} from "./enums";
import { users } from "./users";
import { bikeAssets } from "./fleet";

// ─── System Alerts ───────────────────────────────────────────────────────────

export const systemAlerts = pgTable("system_alerts", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => createId()),
  severity: alertSeverityEnum("severity").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  entityType: alertEntityTypeEnum("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  isAcknowledged: boolean("is_acknowledged").default(false).notNull(),
  acknowledgedBy: text("acknowledged_by"),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  isResolved: boolean("is_resolved").default(false).notNull(),
  resolvedBy: text("resolved_by"),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  recommendedAction: text("recommended_action"),
  bikeId: text("bike_id").references(() => bikeAssets.id),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("system_alerts_severity_idx").on(table.severity),
  index("system_alerts_entity_type_idx").on(table.entityType),
  index("system_alerts_is_acknowledged_idx").on(table.isAcknowledged),
  index("system_alerts_is_resolved_idx").on(table.isResolved),
  index("system_alerts_created_at_idx").on(table.createdAt),
]);

// ─── Risk Assessments ────────────────────────────────────────────────────────

export const riskAssessments = pgTable("risk_assessments", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => createId()),
  entityId: text("entity_id").notNull(),
  entityType: riskEntityTypeEnum("entity_type").notNull(),
  riskLevel: riskLevelEnum("risk_level").notNull(),
  riskScore: integer("risk_score").notNull(),
  assessedAt: timestamp("assessed_at", { withTimezone: true }).defaultNow().notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("risk_assessments_entity_type_idx").on(table.entityType),
  index("risk_assessments_risk_level_idx").on(table.riskLevel),
  index("risk_assessments_assessed_at_idx").on(table.assessedAt),
]);

// ─── Risk Factors ────────────────────────────────────────────────────────────

export const riskFactors = pgTable("risk_factors", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => createId()),
  assessmentId: text("assessment_id")
    .notNull()
    .references(() => riskAssessments.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  score: integer("score").notNull(),
  value: text("value").notNull(),
  isAcceptable: boolean("is_acceptable").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("risk_factors_assessment_id_idx").on(table.assessmentId),
]);

// ─── Audit Log Entries ───────────────────────────────────────────────────────

export const auditLogEntries = pgTable("audit_log_entries", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => createId()),
  actorId: text("actor_id")
    .notNull()
    .references(() => users.id),
  actorName: text("actor_name").notNull(),
  actorRole: userRoleEnum("actor_role").notNull(),
  action: text("action").notNull(),
  category: auditCategoryEnum("category").notNull(),
  targetEntity: text("target_entity").notNull(),
  targetId: text("target_id").notNull(),
  details: text("details").notNull(),
  ipAddress: text("ip_address").notNull(),
  previousEntryHash: text("previous_entry_hash").notNull(),
  entryHash: text("entry_hash").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("audit_log_entries_actor_id_idx").on(table.actorId),
  index("audit_log_entries_category_idx").on(table.category),
  index("audit_log_entries_target_entity_idx").on(table.targetEntity),
  index("audit_log_entries_target_id_idx").on(table.targetId),
  index("audit_log_entries_created_at_idx").on(table.createdAt),
]);

// ─── Relations ───────────────────────────────────────────────────────────────

export const systemAlertsRelations = relations(systemAlerts, ({ one }) => ({
  bike: one(bikeAssets, {
    fields: [systemAlerts.bikeId],
    references: [bikeAssets.id],
  }),
}));

export const riskAssessmentsRelations = relations(riskAssessments, ({ many }) => ({
  factors: many(riskFactors),
}));

export const riskFactorsRelations = relations(riskFactors, ({ one }) => ({
  assessment: one(riskAssessments, {
    fields: [riskFactors.assessmentId],
    references: [riskAssessments.id],
  }),
}));

export const auditLogEntriesRelations = relations(auditLogEntries, ({ one }) => ({
  user: one(users, {
    fields: [auditLogEntries.actorId],
    references: [users.id],
  }),
}));
